language: perl

install:
  - cpanm -n Dist::Zilla
  - dzil authordeps --missing | cpanm -n
  - cpanm -n Alien::Base File::ShareDir File::Which Test::CChecker Text::ParseWords

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.19"

#before_script: /bin/true

script: dzil test

#after_script: /bin/true
