language: perl

install:
  - sudo apt-get update
  - sudo apt-get install bsdtar
  - cpanm -n Dist::Zilla
  - dzil authordeps --missing | cpanm -n
  - cpanm -n Alien::Base File::ShareDir File::Which Test::CChecker Text::ParseWords
  - cpanm -n Dist::Zilla::Plugin::Alien
  - cpanm -n Test::CPAN::Changes Test::EOL Test::Fixme Test::NoTabs Test::Pod::Spelling::CommonMistakes Test::Spelling Test::Strict Test::Version || true

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.19"

#before_script: /bin/true

script: dzil test -v

#after_script: /bin/true
